name: Build

on: #trigger
  workflow_call:
  #push: whenever code is pushed to github the workflow automatically run
  #workflow_call: workflow needed to be called from another 
  #workflow_dispatch: workflow call manually
  #schedule: workflow run at spectific time

jobs: 
  build:
    runs-on: ubantu-latest
    run: echo "commit to docker"
